### ISSUE TITLE
OSError: libiomp5.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by neohunter** [JSchmie/ScrAIbe-WebUI#29]
I"m running ubuntu linux 22.04, installed nvidia tooklit. Trying to run this with docker,

```
❯ docker compose up
[+] Running 1/1
 ✔ Container scraibe_large  Recreated                                                                                                    0.8s
Attaching to scraibe_large
scraibe_large  | Traceback (most recent call last):
scraibe_large  |   File "/opt/conda/lib/python3.10/runpy.py", line 187, in _run_module_as_main
scraibe_large  |     mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
scraibe_large  |   File "/opt/conda/lib/python3.10/runpy.py", line 110, in _get_module_details
scraibe_large  |     __import__(pkg_name)
scraibe_large  |   File "/app/scraibe_webui/__init__.py", line 1, in <module>
scraibe_large  |     from .utils import *
scraibe_large  |   File "/app/scraibe_webui/utils/__init__.py", line 1, in <module>
scraibe_large  |     from .appconfigloader import *
scraibe_large  |   File "/app/scraibe_webui/utils/appconfigloader.py", line 8, in <module>
scraibe_large  |     from torch import set_num_threads
scraibe_large  |   File "/opt/conda/lib/python3.10/site-packages/torch/__init__.py", line 236, in <module>
scraibe_large  |     _load_global_deps()
scraibe_large  |   File "/opt/conda/lib/python3.10/site-packages/torch/__init__.py", line 195, in _load_global_deps
scraibe_large  |     raise err
scraibe_large  |   File "/opt/conda/lib/python3.10/site-packages/torch/__init__.py", line 176, in _load_global_deps
scraibe_large  |     ctypes.CDLL(lib_path, mode=ctypes.RTLD_GLOBAL)
scraibe_large  |   File "/opt/conda/lib/python3.10/ctypes/__init__.py", line 374, in __init__
scraibe_large  |     self._handle = _dlopen(self._name, mode)
scraibe_large  | OSError: libiomp5.so: cannot open shared object file: No such file or directory
scraibe_large exited with code 1

```

**Comment by JSchmie** [comment]
Hello @neohunter, 
Can you maybe provide me more details about your setup? It seems like you are rebuilding the ScrAIbe-WebUI Container locally, so can you share your `docker-compose.yaml` with us? 
Further, did you ensure that you installed the [NVIDIA Container Toolkit](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html) as well as docker itself correctly? 
If so, please share your docker version as well as the version of the NVIDIA Container Toolkit you are using.

**Comment by neohunter** [comment]
I've Nvidia toolkit installed, to reproduce this error I just clone the repository and run 

$ docker compose up

It built the image succesfully, then the error appear, I tried to add

RUN apt update && apt-get install -y libsm6 libxrender1 libfontconfig1 git libomp5

to the Dockerfile, but the error is still appearing.

**Comment by mahenning** [comment]
Hey @neohunter, thanks for raising the issue! I could replicate your error (although I'm not sure why it pops up now as I thought I tested the building and running.. oh well)  

I could fix this on my mchine by changing the base pytorch image in the [Dockerfile](https://github.com/JSchmie/ScrAIbe-WebUI/blob/main/Dockerfile). We will push out the fix in a few days. If you want to fix it earlier, just replace the first (uncommented) line in the `Dockerfile`:
OLD
```
FROM pytorch/pytorch:2.3.0-cuda12.1-cudnn8-runtime
```
NEW
```
FROM pytorch/pytorch:2.3.1-cuda12.1-cudnn8-runtime
```

Please let us know if that fixes the error for you. You may have to delete your docker builder cache or build without cache to make sure the changes are coming through.

**Comment by neohunter** [comment]
I confirm this worked, will create a PR with it
