### ISSUE TITLE
Can I use CPU only ?

### ISSUE THREAD

**Issue by ithakaa** [JSchmie/ScrAIbe-WebUI#41]
Given I do not have an NVIDIA GPU, can I use a CPU ?

If so, how ?

**Comment by JSchmie** [comment]
Hi @ithakaa, 

Yes, you can definitely use a CPU if you don't have access to an NVIDIA GPU. The PyTorch backend will automatically fall back to using the CPU when no GPU is detected, so no special configuration is needed for this. Just be aware that the processing time will be longer on a CPU compared to a GPU.

Additionally, if you want to set up ScrAIbe-WebUI as a web service, you're able to connect it to an SMTP client to send the transcripts via email. You can achieve this by configuring our asynchronous backend, which allows you to upload files and receive the results directly in your inbox. For more details, refer to our guide here: [Customize your WebUI](https://github.com/JSchmie/ScrAIbe-WebUI/blob/main/docs/Customize.md).

If you encounter any issues or have more questions, don’t hesitate to reach out. We’re happy to help!
